BEGIN TRANSACTION;
    INSERT INTO category (category_name) VALUES('American');
    INSERT INTO category (category_name) VALUES('Mexican');
    INSERT INTO category (category_name) VALUES('Japanese');
    INSERT INTO category (category_name) VALUES('Chinese');
    INSERT INTO category (category_name) VALUES('Italian');
    INSERT INTO category (category_name) VALUES('Indian');
    INSERT INTO category (category_name) VALUES('Thai');
    INSERT INTO category (category_name) VALUES('Greek');
    INSERT INTO category (category_name) VALUES('Spanish');
    INSERT INTO category (category_name) VALUES('Mediterranean');
    INSERT INTO category (category_name) VALUES('Lebanese');
    INSERT INTO category (category_name) VALUES('Turkish');
    INSERT INTO category (category_name) VALUES('Korean');
COMMIT TRANSACTION;